### ISSUE TITLE
Port to GTK+ 3

### ISSUE THREAD

**Issue by quozl** [sugarlabs/spirolaterals#8]
Spirolaterals is GTK+ 2 dependent.

(_this is semi-automatic and is not to suggest my interest in the activity_).

**Comment by walterbender** [comment]
I am confused. I am certain I ported Spiralaterals to GTK3 years ago.

**Comment by quozl** [comment]
@walterbender, yes, there's a gtk3 branch.  I hadn't looked for a port, it's just that the master branch was gtk2.  I guess I really should stop noticing things.

@Pro-Panda, would you be so kind as to review and merge the gtk3 branch into master?

**Comment by walterbender** [comment]
Just glad my memory is not completely shot. Apparently I never made a PR to merge my port. Sorry.

**Comment by Pro-Panda** [comment]
@quozl @walterbender 
gtk3 merged into master

Kindly review, thanks
